name: Risco local MQTT
version: 0.4.2
slug: risco-mqtt-local-addon
description: Risco alarm HA integration using local TCP communication and MQTT
url: https://github.com/vanackej/risco-mqtt-local
image: "ghcr.io/vanackej/risco-mqtt-local-addon-{arch}"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  33000/tcp: 33000
ports_description:
  33000/tcp: Socket server for proxy mode
map:
  - config:rw
